import * as schemaPg from './schema_pg';

export const {
  users,
  workOrders,
  columnCatalog,
  columnOptions,
  roleColumnPermissions,
  userColumnOverrides,
  auditLogs,
  stages,
  regions,
  sectors,
  kpiTemplates,
  kpiRules,
  workOrderKpiCache,
  columnGroups,
  columnCategories,
  roleEnum,
  roleDefinitions,
  reportExports,
  workOrderNotes,
  workOrderAttachments,
  importRuns,
  excavationPermits,
  periodicKpiExecutionRules,
  periodicKpiFinancialRule,
  periodicKpiReportSettings,
  periodicKpiMetrics,
  userReportColumnPrefs,
  executiveTargets,
  executiveSectorTargets,
  annualTargetItems,
  reportTemplates,
  integrations,
  sectorAnnualTargets,
  contracts,
  contractAttachments,
  systemSettings,
} = schemaPg as any;
